//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebExam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderMaster
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public int ProductID { get; set; }
        public string ProdName { get; set; }
        public int ProdPrice { get; set; }
        public int ProdQty { get; set; }
        public int ProdTotal { get; set; }
        public string Tag { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual SignUp SignUp { get; set; }
    }
}
